# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\HFView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HFView(object):
    def setupUi(self, HFView):
        HFView.setObjectName(_fromUtf8("HFView"))
        HFView.resize(720, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HFView.sizePolicy().hasHeightForWidth())
        HFView.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Image/serial.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HFView.setWindowIcon(icon)
        self.vLayout0 = QtGui.QVBoxLayout(HFView)
        self.vLayout0.setObjectName(_fromUtf8("vLayout0"))
        self.txtMain = QtGui.QTextEdit(HFView)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.txtMain.setFont(font)
        self.txtMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtMain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtMain.setObjectName(_fromUtf8("txtMain"))
        self.vLayout0.addWidget(self.txtMain)
        self.hLayout1 = QtGui.QHBoxLayout()
        self.hLayout1.setObjectName(_fromUtf8("hLayout1"))
        self.lblDLL = QtGui.QLabel(HFView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDLL.sizePolicy().hasHeightForWidth())
        self.lblDLL.setSizePolicy(sizePolicy)
        self.lblDLL.setObjectName(_fromUtf8("lblDLL"))
        self.hLayout1.addWidget(self.lblDLL)
        self.linDLL = QtGui.QLineEdit(HFView)
        self.linDLL.setObjectName(_fromUtf8("linDLL"))
        self.hLayout1.addWidget(self.linDLL)
        self.btnDLL = QtGui.QPushButton(HFView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDLL.sizePolicy().hasHeightForWidth())
        self.btnDLL.setSizePolicy(sizePolicy)
        self.btnDLL.setObjectName(_fromUtf8("btnDLL"))
        self.hLayout1.addWidget(self.btnDLL)
        self.vLayout0.addLayout(self.hLayout1)
        self.hLayout2 = QtGui.QHBoxLayout()
        self.hLayout2.setObjectName(_fromUtf8("hLayout2"))
        self.lblDis = QtGui.QLabel(HFView)
        self.lblDis.setObjectName(_fromUtf8("lblDis"))
        self.hLayout2.addWidget(self.lblDis)
        self.cmbDis = QtGui.QComboBox(HFView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDis.sizePolicy().hasHeightForWidth())
        self.cmbDis.setSizePolicy(sizePolicy)
        self.cmbDis.setObjectName(_fromUtf8("cmbDis"))
        self.hLayout2.addWidget(self.cmbDis)
        self.btnDis = QtGui.QPushButton(HFView)
        self.btnDis.setObjectName(_fromUtf8("btnDis"))
        self.hLayout2.addWidget(self.btnDis)
        self.vLayout0.addLayout(self.hLayout2)
        self.hLayout3 = QtGui.QHBoxLayout()
        self.hLayout3.setObjectName(_fromUtf8("hLayout3"))
        self.lblStkSel = QtGui.QLabel(HFView)
        self.lblStkSel.setObjectName(_fromUtf8("lblStkSel"))
        self.hLayout3.addWidget(self.lblStkSel)
        self.cmbStkSel = QtGui.QComboBox(HFView)
        self.cmbStkSel.setMinimumSize(QtCore.QSize(58, 0))
        self.cmbStkSel.setMaximumSize(QtCore.QSize(58, 16777215))
        self.cmbStkSel.setObjectName(_fromUtf8("cmbStkSel"))
        self.cmbStkSel.addItem(_fromUtf8(""))
        self.cmbStkSel.addItem(_fromUtf8(""))
        self.cmbStkSel.addItem(_fromUtf8(""))
        self.hLayout3.addWidget(self.cmbStkSel)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hLayout3.addItem(spacerItem)
        self.lblStkSize = QtGui.QLabel(HFView)
        self.lblStkSize.setObjectName(_fromUtf8("lblStkSize"))
        self.hLayout3.addWidget(self.lblStkSize)
        self.linStkSize = QtGui.QLineEdit(HFView)
        self.linStkSize.setMinimumSize(QtCore.QSize(58, 0))
        self.linStkSize.setMaximumSize(QtCore.QSize(58, 16777215))
        self.linStkSize.setMaxLength(5)
        self.linStkSize.setObjectName(_fromUtf8("linStkSize"))
        self.hLayout3.addWidget(self.linStkSize)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayout3.addItem(spacerItem1)
        self.btnRead = QtGui.QPushButton(HFView)
        self.btnRead.setObjectName(_fromUtf8("btnRead"))
        self.hLayout3.addWidget(self.btnRead)
        self.btnParse = QtGui.QPushButton(HFView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnParse.sizePolicy().hasHeightForWidth())
        self.btnParse.setSizePolicy(sizePolicy)
        self.btnParse.setMinimumSize(QtCore.QSize(0, 0))
        self.btnParse.setCheckable(False)
        self.btnParse.setObjectName(_fromUtf8("btnParse"))
        self.hLayout3.addWidget(self.btnParse)
        self.btnClear = QtGui.QPushButton(HFView)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.hLayout3.addWidget(self.btnClear)
        self.vLayout0.addLayout(self.hLayout3)

        self.retranslateUi(HFView)
        QtCore.QMetaObject.connectSlotsByName(HFView)

    def retranslateUi(self, HFView):
        HFView.setWindowTitle(_translate("HFView", "XIVN1987 HardFault Viewer", None))
        self.lblDLL.setText(_translate("HFView", "JLinkARM.dll路径：", None))
        self.btnDLL.setText(_translate("HFView", "...", None))
        self.lblDis.setText(_translate("HFView", "反汇编文件  路径：", None))
        self.btnDis.setText(_translate("HFView", "...", None))
        self.lblStkSel.setText(_translate("HFView", "栈选择：", None))
        self.cmbStkSel.setItemText(0, _translate("HFView", "Auto", None))
        self.cmbStkSel.setItemText(1, _translate("HFView", "MSP", None))
        self.cmbStkSel.setItemText(2, _translate("HFView", "PSP", None))
        self.lblStkSize.setText(_translate("HFView", "栈大小：", None))
        self.linStkSize.setText(_translate("HFView", "32", None))
        self.btnRead.setText(_translate("HFView", "栈读取", None))
        self.btnParse.setText(_translate("HFView", "栈解析", None))
        self.btnClear.setText(_translate("HFView", "清显示", None))

